// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Game$Codenames from "./Game.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as JoinGame$Codenames from "./JoinGame.bs.js";

function make(param) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url.path;
  if (match) {
    if (match[1]) {
      return React.createElement(JoinGame$Codenames.make, { });
    } else {
      return React.createElement(Game$Codenames.make, {
                  id: match[0]
                });
    }
  } else {
    return React.createElement(JoinGame$Codenames.make, { });
  }
}

export {
  make ,
  
}
/* react Not a pure module */
