// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Router$Codenames from "./Router.bs.js";
import * as GameView$Codenames from "./GameView.bs.js";
import * as LobbyView$Codenames from "./LobbyView.bs.js";

function App(Props) {
  var match = React.useState((function () {
          return Router$Codenames.currentRoute(/* () */0);
        }));
  var onChangeRoute = match[1];
  var route = match[0];
  React.useEffect((function () {
          var watchId = Router$Codenames.watchUrl((function (url) {
                  var route = Router$Codenames.fromUrl(url);
                  return Curry._1(onChangeRoute, (function (param) {
                                return route;
                              }));
                }));
          return (function (param) {
                    return Router$Codenames.unwatchUrl(watchId);
                  });
        }), ([]));
  if (route) {
    return React.createElement(GameView$Codenames.make, {
                id: route[0]
              });
  } else {
    return React.createElement(LobbyView$Codenames.make, { });
  }
}

var make = App;

var $$default = App;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
