// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function JoinGame(Props) {
  return React.createElement("main", {
              className: "text-center"
            }, React.createElement("h1", undefined, "Codenames Online"), React.createElement("span", undefined, "Play codenames online across multiple devices"));
}

var make = JoinGame;

export {
  make ,
  
}
/* react Not a pure module */
