// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Slug from "slug";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function LobbyView(Props) {
  var match = React.useState((function () {
          return "turtles";
        }));
  var setRoomName = match[1];
  var roomName = match[0];
  var onSubmit = function ($$event) {
    $$event.preventDefault();
    var s = Slug.default(roomName);
    return ReasonReactRouter.push("/" + s);
  };
  return React.createElement("main", {
              className: "mt-12 container mx-auto max-w-md text-center"
            }, React.createElement("h1", {
                  className: "font-sans text-4xl mb-2"
                }, "Codenames Online"), React.createElement("p", {
                  className: "font-sans text-md"
                }, "Play Codenames online across multiple devices on a shared board. To create a new game or join an existing\n                     game, enter a game identifier and click Join Game."), React.createElement("div", {
                  className: "h-8"
                }), React.createElement("form", {
                  className: "w-3/4 mx-auto flex items-center",
                  onSubmit: onSubmit
                }, React.createElement("input", {
                      className: "block w-full h-12 px-4 py-3 leading-tight text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-white",
                      autoFocus: true,
                      placeholder: "Game Code",
                      type: "text",
                      value: roomName,
                      onChange: (function ($$event) {
                          return Curry._1(setRoomName, $$event.target.value);
                        })
                    }), React.createElement("button", {
                      className: "flex-none h-12 py-2 px-4 bg-blue-400 block appearance-none text-white",
                      type: "submit"
                    }, "Join Game")));
}

var make = LobbyView;

export {
  make ,
  
}
/* slug Not a pure module */
