// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function toUrl(r) {
  if (r) {
    return "/" + r[0];
  } else {
    return "/";
  }
}

function fromUrl(url) {
  var match = url.path;
  if (match && !match[1]) {
    return /* Game */[match[0]];
  } else {
    return /* Lobby */0;
  }
}

function push(r) {
  return ReasonReactRouter.push(toUrl(r));
}

function currentRoute(param) {
  return fromUrl(ReasonReactRouter.dangerouslyGetInitialUrl(/* () */0));
}

var watchUrl = ReasonReactRouter.watchUrl;

var unwatchUrl = ReasonReactRouter.unwatchUrl;

export {
  toUrl ,
  fromUrl ,
  watchUrl ,
  unwatchUrl ,
  push ,
  currentRoute ,
  
}
/* ReasonReactRouter Not a pure module */
