// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function getColor(color) {
  switch (color) {
    case /* Black */0 :
        return "black";
    case /* Blue */1 :
        return "blue";
    case /* Red */2 :
        return "red";
    case /* Neutral */3 :
        return "gray";
    
  }
}

export {
  getColor ,
  
}
/* No side effect */
