// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function toColorString(color) {
  switch (color) {
    case /* Black */0 :
        return "black";
    case /* Blue */1 :
        return "blue";
    case /* Red */2 :
        return "red";
    case /* Neutral */3 :
        return "gray";
    
  }
}

var tiles = [
  {
    word: "LEMONS",
    selected: false,
    color: /* Black */0
  },
  {
    word: "WATER",
    selected: false,
    color: /* Neutral */3
  },
  {
    word: "ORANGE",
    selected: false,
    color: /* Blue */1
  },
  {
    word: "COMPUTER",
    selected: false,
    color: /* Red */2
  },
  {
    word: "DOLPHIN",
    selected: false,
    color: /* Blue */1
  },
  {
    word: "ALASKAN",
    selected: false,
    color: /* Red */2
  },
  {
    word: "ANTARTICA",
    selected: false,
    color: /* Blue */1
  },
  {
    word: "TELEVISION",
    selected: false,
    color: /* Red */2
  },
  {
    word: "PIEKARCZYK",
    selected: false,
    color: /* Blue */1
  },
  {
    word: "MONKEY",
    selected: false,
    color: /* Neutral */3
  },
  {
    word: "KITCHEN",
    selected: false,
    color: /* Neutral */3
  },
  {
    word: "REFRIGERATOR",
    selected: false,
    color: /* Neutral */3
  },
  {
    word: "BLUEBERRIES",
    selected: false,
    color: /* Blue */1
  },
  {
    word: "TILES",
    selected: false,
    color: /* Red */2
  },
  {
    word: "FLOOR",
    selected: false,
    color: /* Blue */1
  },
  {
    word: "CONSOLE",
    selected: false,
    color: /* Red */2
  },
  {
    word: "LAPTOP",
    selected: false,
    color: /* Blue */1
  },
  {
    word: "MONITOR",
    selected: false,
    color: /* Red */2
  },
  {
    word: "MATTHEWS",
    selected: false,
    color: /* Blue */1
  },
  {
    word: "ZEBRA",
    selected: false,
    color: /* Neutral */3
  },
  {
    word: "DESK",
    selected: false,
    color: /* Neutral */3
  },
  {
    word: "FRESH",
    selected: false,
    color: /* Red */2
  },
  {
    word: "PEPSI",
    selected: false,
    color: /* Neutral */3
  },
  {
    word: "MOUSE",
    selected: false,
    color: /* Blue */1
  },
  {
    word: "KEYBOARD",
    selected: false,
    color: /* Red */2
  }
];

export {
  toColorString ,
  tiles ,
  
}
/* No side effect */
